### ISSUE TITLE
Update innerscope for Python 3.12

### ISSUE THREAD

**Issue by connorferster** [eriknw/innerscope#25]
Hi @eriknw,

Just wanted to check-in to see if you have time to update innerscope for Python 3.12 compatibility :)

Thanks so much!

**Comment by eriknw** [comment]
Sorry for the delay! I've had lot of, um, "adventures" since Python 3.12 was released (some good, some less so).

Anyway, I just released `innerscope` 0.7.0, which supports Python 3.12.

`innerscope` has two ways to perform its magic: an easy way and a hard way. The hard way has always been the default, but 0.7.0 only supports the "easy" way for Python 3.12. It should work 🤞. The easy way will also be the default for any future versions of Python (you know, just in case I get delayed again, this default should allow `handcalcs` to still work). I'll try to get the "hard" way to work too.

Thanks for the gentle nudges, patience, and understanding. I think future Python releases should go more smoothly. Please let me know if you encounter any issues!

**Comment by connorferster** [comment]
@eriknw Thanks so much! As Brett Cannon says, "Every commit is a gift" in open-source. I am grateful for this one especially 😄 

Interested to hear more about the easy way and hard way: is the hard way more robust or faster or something? What is the motivation for the hard way given the easy way exists?

**Comment by eriknw** [comment]
I love that sentiment, thank you!

The hard way, `"bytecode"`, is faster. It does some weird things and recompiles the function using new bytecode. This is hard because Python changes bytecode every major release. It's been robust though, and pretty fun to figure out :joy:

The easy way, `"trace"`, uses Python tracing (`sys.settrace`). It's pretty slick too, and should be solid. The implementation is pretty simple. The downsides are that it's slower, and it _may_ interact poorly if other tools try to use trace functions. Hmm, looking at this now, maybe I should use `sys.call_tracing` instead (see? what a learning experience!). Heh, and this method probably doesn't work if the function has a falsy `__cantrace__` attribute, which, uh, probably shouldn't happen.

If they're both solid, then why have both? Mostly as a learning experience. The "easy" way may become the default in the future, so using it by default for Python 3.12 for a time is a good experiment.

lol, I should probably document these better, but it's also fun to have `innerscope` be somewhat mysterious!
